# Generated by Django 3.1.4 on 2020-12-19 15:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20201219_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
